name: CI
on:
  push:
    branches:
      - main
jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/a958faed8c1d9f46bd966b474e662394/purge_cache"
          method: "POST"
          bearerToken: ${{ secrets.CF_API_TOKEN }}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "purge_everything": true }'
