# .github/workflows/theme-settings.yml
name: Theme settings
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  theme_settings:
    uses: Shopify/theme-settings-validation/.github/workflows/validate-settings.yml@main
    with:
      head_ref: ${{ github.head_ref }}
      owner_repo: ${{ github.repository }}
      repo_name: ${{ github.event.repository.name }}
      pr_html_url: ${{ github.event.pull_request.html_url }}
    secrets: inherit
